# Generated by Django 5.0.6 on 2024-05-16 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
